# Generated by Django 3.1 on 2022-01-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220103_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categroy_name',
            new_name='category_name',
        ),
    ]
